import { PrismaClient, VehicleType } from '@prisma/client'

type ReferencePriceEntry = {
  brand: string
  model: string
  type: VehicleType
  baseYear: number
  basePrice: number
  depreciationPerKm: number
  notes?: string
}

// Precios de referencia extraídos de Wallapop, coches.net y Autoscout24 (mercado español).
// basePrice: valor de mercado orientativo en euros para el año indicado (vehículo en buen estado, km bajos).
// depreciationPerKm: reducción de valor en euros por cada km adicional.
export const REFERENCE_PRICES: ReferencePriceEntry[] = [
  // ─── CAMPER VANS ───────────────────────────────────────────────────────────
  {
    brand: 'Volkswagen',
    model: 'California Ocean',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 65000,
    depreciationPerKm: 0.18,
  },
  {
    brand: 'Volkswagen',
    model: 'California Beach',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 52000,
    depreciationPerKm: 0.15,
  },
  {
    brand: 'Volkswagen',
    model: 'California 6.1 Ocean',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 70000,
    depreciationPerKm: 0.2,
  },
  {
    brand: 'Volkswagen',
    model: 'Crafter Grand California',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 65000,
    depreciationPerKm: 0.17,
  },
  {
    brand: 'Mercedes-Benz',
    model: 'Marco Polo',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 72000,
    depreciationPerKm: 0.2,
    notes: 'Basado en Clase V',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'Marco Polo Activity',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 68000,
    depreciationPerKm: 0.18,
  },
  {
    brand: 'Mercedes-Benz',
    model: 'Sprinter Camper',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 60000,
    depreciationPerKm: 0.16,
    notes: 'Conversión sobre Sprinter 316/319',
  },
  {
    brand: 'Ford',
    model: 'Transit Custom Nugget',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 52000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Ford',
    model: 'Transit Custom Nugget Plus',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 58000,
    depreciationPerKm: 0.15,
  },
  {
    brand: 'Fiat',
    model: 'Ducato Camper',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 38000,
    depreciationPerKm: 0.1,
    notes: 'Conversión media sobre Ducato L3H2',
  },
  {
    brand: 'Fiat',
    model: 'Ducato Camper XL',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 44000,
    depreciationPerKm: 0.11,
    notes: 'Conversión larga sobre Ducato L4H2',
  },
  {
    brand: 'Renault',
    model: 'Trafic SpaceClass',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 33000,
    depreciationPerKm: 0.09,
  },
  {
    brand: 'Citroën',
    model: 'SpaceTourer Camper',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 30000,
    depreciationPerKm: 0.08,
  },
  {
    brand: 'Peugeot',
    model: 'Traveller Camper',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 28000,
    depreciationPerKm: 0.07,
  },
  {
    brand: 'Opel',
    model: 'Zafira Life Camper',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 30000,
    depreciationPerKm: 0.08,
  },
  {
    brand: 'Toyota',
    model: 'Proace Verso Camper',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 32000,
    depreciationPerKm: 0.08,
  },
  {
    brand: 'Westfalia',
    model: 'Kepler Six',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 58000,
    depreciationPerKm: 0.15,
  },
  {
    brand: 'Westfalia',
    model: 'Kepler One',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 52000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Hymer',
    model: 'Venture S',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 62000,
    depreciationPerKm: 0.16,
  },
  {
    brand: 'Adria',
    model: 'Twin',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 52000,
    depreciationPerKm: 0.13,
  },
  {
    brand: 'Adria',
    model: 'Twin Supreme',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 60000,
    depreciationPerKm: 0.16,
  },
  {
    brand: 'Carado',
    model: 'Banff',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 50000,
    depreciationPerKm: 0.13,
  },
  {
    brand: 'Knaus',
    model: 'BoxStar',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 50000,
    depreciationPerKm: 0.13,
  },
  {
    brand: 'Roller Team',
    model: 'Auto-Roller',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 42000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'Sunlight',
    model: 'Van 47',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 48000,
    depreciationPerKm: 0.12,
  },
  {
    brand: 'Chausson',
    model: 'Van 594',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 54000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Dethleffs',
    model: 'Globevan',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 55000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'LMC',
    model: 'Innova Camper',
    type: VehicleType.CAMPER,
    baseYear: 2021,
    basePrice: 46000,
    depreciationPerKm: 0.12,
  },
  {
    brand: 'Wingamm',
    model: 'Oasi 690G',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 56000,
    depreciationPerKm: 0.15,
  },
  {
    brand: 'Trigano',
    model: 'Tribute 640 Camper',
    type: VehicleType.CAMPER,
    baseYear: 2020,
    basePrice: 38000,
    depreciationPerKm: 0.1,
  },

  // ─── AUTOCARAVANAS ─────────────────────────────────────────────────────────
  {
    brand: 'Hymer',
    model: 'B-Class MobiLine 560',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2019,
    basePrice: 52000,
    depreciationPerKm: 0.12,
    notes: 'Perfilada sobre Fiat Ducato',
  },
  {
    brand: 'Hymer',
    model: 'B-Class 570',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 62000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Hymer',
    model: 'B-Class 580',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 68000,
    depreciationPerKm: 0.16,
  },
  {
    brand: 'Hymer',
    model: 'T-Class S 698',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 47000,
    depreciationPerKm: 0.11,
    notes: 'Capuchina (alcoba frontal)',
  },
  {
    brand: 'Hymer',
    model: 'Exsis-i 580',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 98000,
    depreciationPerKm: 0.25,
    notes: 'Integrada premium',
  },
  {
    brand: 'Adria',
    model: 'Coral 600 SL',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 52000,
    depreciationPerKm: 0.12,
  },
  {
    brand: 'Adria',
    model: 'Coral XL 670 SF',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 62000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Adria',
    model: 'Matrix Plus 670 SC',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 90000,
    depreciationPerKm: 0.22,
    notes: 'Integrada',
  },
  {
    brand: 'Adria',
    model: 'Compact SP',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 39000,
    depreciationPerKm: 0.09,
    notes: 'Compacta, longitud ≤6m',
  },
  {
    brand: 'Adria',
    model: 'Sonic Plus 700 SL',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 80000,
    depreciationPerKm: 0.2,
    notes: 'Integrada gran formato',
  },
  {
    brand: 'Knaus',
    model: 'Sudwind 630 LG',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 50000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'Knaus',
    model: 'Sun Ti 700 LFG',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 70000,
    depreciationPerKm: 0.16,
  },
  {
    brand: 'Knaus',
    model: 'Van Ti 650 MEG',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 60000,
    depreciationPerKm: 0.14,
    notes: 'Semi-integrada compacta',
  },
  {
    brand: 'Knaus',
    model: 'Sport TI 700 MEG',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2022,
    basePrice: 74000,
    depreciationPerKm: 0.17,
  },
  {
    brand: 'Dethleffs',
    model: 'Trend T 7057 EB',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 42000,
    depreciationPerKm: 0.1,
    notes: 'Perfilada entry-level',
  },
  {
    brand: 'Dethleffs',
    model: 'Esprit T 7150 EB',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 50000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'Dethleffs',
    model: 'Globe T 7857 ET',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 46000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'Dethleffs',
    model: 'Pulse T 7051 EB',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 54000,
    depreciationPerKm: 0.12,
  },
  {
    brand: 'Chausson',
    model: '630',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 52000,
    depreciationPerKm: 0.12,
  },
  {
    brand: 'Chausson',
    model: '757 UA',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 66000,
    depreciationPerKm: 0.16,
    notes: 'Capuchina queen bed',
  },
  {
    brand: 'Chausson',
    model: '720 Welcome Premium',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 60000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Chausson',
    model: 'Welcome 60',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 54000,
    depreciationPerKm: 0.12,
  },
  {
    brand: 'Carado',
    model: 'T 447',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 46000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'Carado',
    model: 'T 337',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 42000,
    depreciationPerKm: 0.1,
    notes: 'Perfilada compacta',
  },
  {
    brand: 'Carado',
    model: 'I 338',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 64000,
    depreciationPerKm: 0.15,
    notes: 'Integrada compacta',
  },
  {
    brand: 'Carado',
    model: 'A 461',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 80000,
    depreciationPerKm: 0.2,
    notes: 'Integrada clase A',
  },
  {
    brand: 'Roller Team',
    model: 'Granduca 294',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 44000,
    depreciationPerKm: 0.1,
  },
  {
    brand: 'Roller Team',
    model: 'Kronos 695 M',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 58000,
    depreciationPerKm: 0.13,
  },
  {
    brand: 'Roller Team',
    model: 'Livingstone 5',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 50000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'Sunlight',
    model: 'T 68',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 44000,
    depreciationPerKm: 0.1,
  },
  {
    brand: 'Sunlight',
    model: 'A 70',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 62000,
    depreciationPerKm: 0.14,
    notes: 'Integrada',
  },
  {
    brand: 'Pilote',
    model: 'G740 LJ Sensation',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 60000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Pilote',
    model: 'Pacific P716',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 72000,
    depreciationPerKm: 0.17,
    notes: 'Integrada francesa',
  },
  {
    brand: 'Rapido',
    model: '676',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 57000,
    depreciationPerKm: 0.13,
  },
  {
    brand: 'Rapido',
    model: '896F',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 80000,
    depreciationPerKm: 0.2,
  },
  {
    brand: 'Hobby',
    model: 'Optima De Luxe T 65 GH',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 60000,
    depreciationPerKm: 0.14,
  },
  {
    brand: 'Hobby',
    model: 'Siesta T 65 HQ',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 52000,
    depreciationPerKm: 0.12,
  },
  {
    brand: 'Hobby',
    model: 'Premium T 65 GH',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2022,
    basePrice: 70000,
    depreciationPerKm: 0.16,
  },
  {
    brand: 'LMC',
    model: 'Innova 650 G',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 47000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'LMC',
    model: 'Explorer T 630 G',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 57000,
    depreciationPerKm: 0.13,
  },
  {
    brand: 'Carthago',
    model: 'Chic C-Line I 50',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 118000,
    depreciationPerKm: 0.3,
    notes: 'Integrada lujo',
  },
  {
    brand: 'Carthago',
    model: 'C-Tourer I 138',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 90000,
    depreciationPerKm: 0.22,
  },
  {
    brand: 'Bürstner',
    model: 'Lyseo TD 744',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 74000,
    depreciationPerKm: 0.18,
  },
  {
    brand: 'Bürstner',
    model: 'Ixeo Time IT 706',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 64000,
    depreciationPerKm: 0.15,
  },
  {
    brand: 'Bürstner',
    model: 'Minimax T 680',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 56000,
    depreciationPerKm: 0.13,
  },
  {
    brand: 'Trigano',
    model: 'Tribute 640',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 40000,
    depreciationPerKm: 0.09,
    notes: 'Entry-level francesa',
  },
  {
    brand: 'Trigano',
    model: 'Vision 554',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 48000,
    depreciationPerKm: 0.11,
  },
  {
    brand: 'Niesmann+Bischoff',
    model: 'Flair i 930 LE',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 128000,
    depreciationPerKm: 0.32,
    notes: 'Integrada top de gama',
  },
  {
    brand: 'Laika',
    model: 'Ecovip L 3109',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2021,
    basePrice: 68000,
    depreciationPerKm: 0.16,
    notes: 'Italiana, muy popular en España',
  },
  {
    brand: 'Itineo',
    model: 'MB 700',
    type: VehicleType.AUTOCARAVANA,
    baseYear: 2020,
    basePrice: 57000,
    depreciationPerKm: 0.13,
  },
]

export async function seedReferencePrices(db: PrismaClient) {
  console.log('Seeding reference prices…')

  let created = 0
  let updated = 0

  for (const entry of REFERENCE_PRICES) {
    const result = await db.referencePrice.upsert({
      where: {
        brand_model_type_baseYear: {
          brand: entry.brand,
          model: entry.model,
          type: entry.type,
          baseYear: entry.baseYear,
        },
      },
      update: {
        basePrice: entry.basePrice,
        depreciationPerKm: entry.depreciationPerKm,
        notes: entry.notes ?? null,
      },
      create: {
        brand: entry.brand,
        model: entry.model,
        type: entry.type,
        baseYear: entry.baseYear,
        basePrice: entry.basePrice,
        depreciationPerKm: entry.depreciationPerKm,
        notes: entry.notes ?? null,
      },
    })

    if (result.createdAt.getTime() === result.updatedAt.getTime()) {
      created++
    } else {
      updated++
    }
  }

  console.log(`  ✓ ${created} creadas, ${updated} actualizadas (${REFERENCE_PRICES.length} total)`)
}
